name: Release Package

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Library
        run: |
            python -m pip install .
            python -m pip install setuptools

      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Check version
        run: |
          LIBRARY_VERSION=$(dnabc.py --version)
          GITHUB_VERSION=${{ steps.get_version.outputs.version-without-v }}
          if [[ $LIBRARY_VERSION == $GITHUB_VERSION ]]; then
            echo "Versions match, continuing..."
          else
            echo "Versions don't match, exiting..."
            echo "Library version: $LIBRARY_VERSION"
            echo "GitHub version: $GITHUB_VERSION"
            exit 1
          fi

  run-tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit